language: node_js
node_js: lts/*
sudo: false
addons:
  chrome: stable
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g @lhci/cli@0.3.x
script:
  - yarn validate
  - yarn export
install:
  - yarn install
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: 'out'
  on:
    branch: master
env:
  matrix:
    secure: $GITHUB_TOKEN
notifications:
  email:
    - vkumar59@sapient.com
    - akakroo@sapient.com
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - lhci autorun --upload.target=temporary-public-storage
